[Twitch]
# get your twitch token at: https://twitchtokengenerator.com/ -> Bot Chat Token
ACCESS_TOKEN="werueioriewo"
CHANNEL="myTwitchChannel"
BOT_PREFIX=["?","!"]
MESSAGE_PREFIX="[requestnonsense]"

[Local]
QUEUE_FILE="./queue.bin"
SONGLIST="./songlist.csv"
INSTRUMENTS=["Lead","Rhythm","Bass"]
LIST_DELIMITER=";"
LIST_CFSM=true

[HACKMD]
# get your hackmd token at https://hackmd.io/
HACKMDTOKEN="jiwerjeorijwe"
HACKMDTAG="requestnonsense"
QUEUETITLE="mystische Warteschlange"
LISTTITLE="mystische Songliste"